# DeluxeMenus 1.13.3-Release main configuration file
# 
# A full wiki on how to use this plugin can be found at:
# https://github.com/help-chat/DeluxeMenus/wiki

debug: false
check_updates: true
gui_menus:
  malloc_menu:
    file: malloc_menu.yml
  chat_menu:
    file: chat_menu.yml
  stats_menu:
    file: stats_menu.yml
  community_goals:
    file: community_goals.yml
